### ISSUE TITLE
Guitarix forums seem inactive... where should I report bugs?

### ISSUE THREAD

**Issue by cyrusadkisson** [brummer10/GxPlugins.lv2#15]
Again, sorry for posting this here. I feel like guitarix core needs to be on github to be a healthy project so people can submit pull requests and report issues. I have several to report and don't know where to put them.

**Comment by brummer10** [comment]
Hi, yes, guitarix forum is closed because of the new General Data Protection Regulation (GDPR) in the EU. This makes it a to much hassle for me to maintain it. 
Communication is now preferred over REDDIT r/Guitarix.
Bug reports are welcome on  https://sourceforge.net/p/guitarix/bugs/
If you ain't have a sourceforge account you could report there Anonymous.

**Comment by cyrusadkisson** [comment]
Stupid GDPR.
