### ISSUE TITLE
Open sourcing .dsp

### ISSUE THREAD

**Issue by fiwe-studio** [brummer10/GxPlugins.lv2#17]
Hello brummer10,
As you know we are using your great GxPluginsV2 for https://fiwe.studio
We have a shim on top of the plugin/gx_<PluginName>.cpp lv2 files that is itself a shim on top of the compiled dsp/<PluginName>.cc from the faust .dsp presumably.
It would be more efficient for us to use the .dsp file directly with our internal faust compiler, so I was wondering whether there is any particular reason why you haven't open-sourced the .dsp files ? :)
Thank you!

**Comment by brummer10** [comment]
Hi

Didn't you've a LV2 wrapper anyway in fiwe? 
A couple of the logic/coupling in the GxPlugins is done in the lv2 wrapper to the from_faust.cc files, a couple of them been hand edited afterwards,  so, using the faust files directly to reassemble the GxPlugins is discouraged from here. You really need to know what you do. If you still prefer that, then, I could provide the faust sources to you, but, will ask you to use your own names for the plugs you made out of them, means at least remove the Gx prefix from the plugs you incorporate this way. 

regards
hermann

**Comment by fiwe-studio** [comment]
Ah ok then I'll stay with the LV2 wrapper. I was just trying to save a few CPU cycles but if the exact same sound cannot be obtained from the .dsp we shouldn't use it.
Thanks!

**Comment by brummer10** [comment]
You should be aware that GxPlugins now use X11 interfaces (GUI), a update of your fork may be interesting for you. Also, I see you've removed the resampler from the plugs. That's a bad idea. It's, a downsampler in this case, means, that is what allow you to use them at a host frequency of 96kHz. When remove it, unexpected behave is to be expected. Otherwise it ain't interact at all.  
We  talk about IIR filters here, which are designed for 48kHz. They work on any level below, and at any level above, up to double frequency, at this point we need to reduce sampling frequency in order to ensure working stable. A bonus point at this point is, it will reduce CPU usage, not increase it.

regards
hermann
